export const FLAIRS = [
  { id: 'kabutar_science', label: 'kabutar science', color: 'text-black', bg: 'bg-cyan-400', border: 'border-cyan-400' },
  { id: 'alecc_daddy', label: 'Alecc Daddy', color: 'text-black', bg: 'bg-yellow-400', border: 'border-yellow-400' },
  { id: 'dropper_topper', label: 'dropper >>> topper', color: 'text-black', bg: 'bg-lime-400', border: 'border-lime-400' },
  { id: 'nta_victim', label: "NTA's VICTIM", color: 'text-black', bg: 'bg-rose-400', border: 'border-rose-400' },
  { id: 'dropper_yug', label: 'DROPPER YUG', color: 'text-white', bg: 'bg-fuchsia-600', border: 'border-fuchsia-600' },
  { id: 'air_247', label: 'AIR 247', color: 'text-white', bg: 'bg-violet-600', border: 'border-violet-600' },
  { id: 'eye_eye_tea_bamboo', label: 'eye eye tea bamboo', color: 'text-black', bg: 'bg-emerald-400', border: 'border-emerald-400' },
  { id: 'aids_sangh', label: 'AIDS -ALL INDIA DROPER SANGH', color: 'text-black', bg: 'bg-orange-500', border: 'border-orange-500' },
  { id: 'cengage_paglu', label: 'CENGAGE PAGLU', color: 'text-black', bg: 'bg-blue-400', border: 'border-blue-400' },
  { id: 'iit_rod', label: 'IIT ALUMINIUM ROD', color: 'text-black', bg: 'bg-slate-400', border: 'border-slate-400' },
  { id: 'future_mistry', label: 'FUTURE MISTRY', color: 'text-white', bg: 'bg-indigo-600', border: 'border-indigo-600' },
  { id: 'peedabloo', label: 'PEEDABLOO', color: 'text-white', bg: 'bg-black', border: 'border-white/20' },
  { id: 'white_coat', label: 'WHITE COAT', color: 'text-sky-600', bg: 'bg-white', border: 'border-sky-600' },
  { id: 'alien', label: 'ALIEN', color: 'text-white', bg: 'bg-green-700', border: 'border-green-700' },
  { id: 'kaddu_gang', label: 'KADDU GANG', color: 'text-black', bg: 'bg-yellow-500', border: 'border-yellow-500' },
  { id: 'fan_rope_dealer', label: 'FAN AND ROPE DEALER', color: 'text-white', bg: 'bg-gray-800', border: 'border-gray-800' },
  { id: 'kyu_nhi_ho_rhi_padhaai', label: 'KYU NHI HO RHI PADHAAI', color: 'text-white', bg: 'bg-red-600', border: 'border-red-600' },
];
